### ISSUE TITLE
ISSUE: [PLM] Randomly not able to get a m3u or XML EPG file

### ISSUE THREAD

**Issue by babsonnexus** [babsonnexus/stream-link-manager-for-channels#16]
Sometimes, while retrieving an m3u or EPG, PLM will give up after just a few seconds instead of waiting for it to load. It is inconsistent behavior and hard to track down as the same link can work and an hour later not work. It seems particularly prevalent with with [Samsung TV+](https://community.getchannels.com/t/samsung-tv-plus-for-channels/41033) and, to a lesser extend, [DistroTV](https://community.getchannels.com/t/distrotv/32985/17).

**Comment by babsonnexus** [comment]
> **chDVRuser, post:3, topic:41719**
> I see the same problem with Samsung TV+ just using it as intended with Channels.
> So far this month (updating playlist/xml hourly)

```
2024/10/05 12:15:09.694490 [ERR] Unexpected m3u response for SamsungTVPlus: 500 Internal Server Error
2024/10/05 13:15:13.406329 [ERR] Failed to request m3u for SamsungTVPlus: Get "http://192.168.1.3:8182/playlist.m3u8": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2024/10/07 09:15:11.719993 [ERR] Unexpected m3u response for SamsungTVPlus: 500 Internal Server Error
2024/10/24 11:15:14.031980 [ERR] Failed to request m3u for SamsungTVPlus: Get "http://192.168.1.3:8182/playlist.m3u8": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2024/10/26 03:15:13.382200 [ERR] Failed to request m3u for SamsungTVPlus: Get "http://192.168.1.3:8182/playlist.m3u8": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2024/10/26 15:15:13.825703 [ERR] Failed to request m3u for SamsungTVPlus: Get "http://192.168.1.3:8182/playlist.m3u8": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

> The container takes too long to respond to Channels which leads to an exception in the container
> BrokenPipeError: [Errno 32] Broken pipe

> The container log usually looks like this

```
2024-10-26T22:15:21.774874689Z Including channels from regions: ['us']
2024-10-26T22:15:21.775205252Z 192.168.144.1 - - [26/Oct/2024 15:15:21] "GET /playlist.m3u8 HTTP/1.1" 200 -
2024-10-26T22:15:21.777449328Z 192.168.144.1 - - [26/Oct/2024 15:15:21] "GET /playlist.m3u8 HTTP/1.1" 500 -
2024-10-26T22:15:21.777787699Z ----------------------------------------
2024-10-26T22:15:21.777908451Z Exception occurred during processing of request from ('192.168.144.1', 44480)
2024-10-26T22:15:21.779876350Z Traceback (most recent call last):
2024-10-26T22:15:21.780945769Z   File "/usr/src/app/./app.py", line 48, in do_GET
2024-10-26T22:15:21.781204142Z     routes[func]()
2024-10-26T22:15:21.781378660Z   File "/usr/src/app/./app.py", line 96, in _playlist
2024-10-26T22:15:21.781524574Z     self.wfile.write(f'#EXTINF:-1 channel-id="{channel_id}" tvg-id="{key}" tvg-logo="{logo}" group-title="{group}"{chno},{name}\n{url}\n'.encode('utf8'))
2024-10-26T22:15:21.781676874Z   File "/usr/local/lib/python3.12/socketserver.py", line 840, in write
2024-10-26T22:15:21.781803555Z     self._sock.sendall(b)
2024-10-26T22:15:21.781905473Z BrokenPipeError: [Errno 32] Broken pipe
2024-10-26T22:15:21.782009662Z 
2024-10-26T22:15:21.782094622Z During handling of the above exception, another exception occurred:
2024-10-26T22:15:21.782198372Z 
2024-10-26T22:15:21.782279478Z Traceback (most recent call last):
2024-10-26T22:15:21.782994632Z   File "/usr/local/lib/python3.12/socketserver.py", line 692, in process_request_thread
2024-10-26T22:15:21.783216446Z     self.finish_request(request, client_address)
2024-10-26T22:15:21.783465992Z   File "/usr/local/lib/python3.12/socketserver.py", line 362, in finish_request
2024-10-26T22:15:21.783672885Z     self.RequestHandlerClass(request, client_address, self)
2024-10-26T22:15:21.783819644Z   File "/usr/src/app/./app.py", line 23, in __init__
2024-10-26T22:15:21.783932717Z     super().__init__(*args, **kwargs)
2024-10-26T22:15:21.784028259Z   File "/usr/local/lib/python3.12/socketserver.py", line 761, in __init__
2024-10-26T22:15:21.784128136Z     self.handle()
2024-10-26T22:15:21.784226555Z   File "/usr/local/lib/python3.12/http/server.py", line 436, in handle
2024-10-26T22:15:21.784396009Z     self.handle_one_request()
2024-10-26T22:15:21.784528152Z   File "/usr/local/lib/python3.12/http/server.py", line 424, in handle_one_request
2024-10-26T22:15:21.784892417Z     method()
2024-10-26T22:15:21.785022207Z   File "/usr/src/app/./app.py", line 50, in do_GET
2024-10-26T22:15:21.785133745Z     self._error(e)
2024-10-26T22:15:21.785230833Z   File "/usr/src/app/./app.py", line 27, in _error
2024-10-26T22:15:21.785374280Z     self.end_headers()
2024-10-26T22:15:21.785496450Z   File "/usr/local/lib/python3.12/http/server.py", line 538, in end_headers
2024-10-26T22:15:21.785606428Z     self.flush_headers()
2024-10-26T22:15:21.785697012Z   File "/usr/local/lib/python3.12/http/server.py", line 542, in flush_headers
2024-10-26T22:15:21.785800081Z     self.wfile.write(b"".join(self._headers_buffer))
2024-10-26T22:15:21.785899353Z   File "/usr/local/lib/python3.12/socketserver.py", line 840, in write
2024-10-26T22:15:21.785999264Z     self._sock.sendall(b)
2024-10-26T22:15:21.786087818Z BrokenPipeError: [Errno 32] Broken pipe
2024-10-26T22:15:21.786179593Z ----------------------------------------
```

> See my post in [Samsung TV Plus for Channels - #35 by chDVRuser ](https://community.getchannels.com/t/samsung-tv-plus-for-channels/41033/35)

**Comment by babsonnexus** [comment]
A potential workaround is being implemented in the next version. Will be further monitoring to make sure it resolves the issue.

**Comment by babsonnexus** [comment]
Monitoring as of v2024.11.02.0936

**Comment by babsonnexus** [comment]
I noticed today that in one example, Tubi Gracenote-excluded worked fine, but when it tried to retrieve Tubi Gracenote-included it failed with a 500 error (6 minutes later).

```
[DEBUG | 2024-11-12 06:00:13,475] - Starting new HTTP connection (1): localhost:7970
[DEBUG | 2024-11-12 06:00:40,526] - http://localhost:7970 "GET /tubi/playlist.m3u?gracenote=exclude HTTP/1.1" 200 9561
[DEBUG | 2024-11-12 06:00:40,526] - Encoding detection: utf_8 is most likely the one.
[DEBUG | 2024-11-12 06:00:40,542] - Starting new HTTP connection (1): localhost:7970
[DEBUG | 2024-11-12 06:06:07,388] - http://localhost:7970 "GET /tubi/playlist.m3u?gracenote=include HTTP/1.1" 500 265
```

When I manually ran later in the day, there was no issue, but during that in-between time, the stations were removed. Since there are no additional log lines in between, that means that it was trying during that timeframe with the initial connection and never tried again, meaning it accepted the 500 error as valid. I think I need to put a timeout on the connection so it can try again, and also make sure a 500 triggers a retry, too.

**Comment by babsonnexus** [comment]
This modification is ready to test in the next release

**Comment by babsonnexus** [comment]
Monitoring in v2024.11.13.1347

**Comment by babsonnexus** [comment]
Solution appears to be working. As such, this will be closed in the next release.

**Comment by babsonnexus** [comment]
Closed in:

https://github.com/babsonnexus/stream-link-manager-for-channels/releases/tag/v2024.11.18.1135
